name: Rollins Real Estate Management
favicon: null
layout_spectrum: 0.5868037801701576
typography_spectrum: 0.91482571978122
author:
  name: Frank Landolt
  email: flandolt@rrem.com
  url: ''
navigation:
  - name: Services
    id: b3974b0b-e020-4739-8a4c-6f90b30308fd
    type: content
  - name: Fairview
    id: 60552014-7f8d-4dae-95ec-1fad8dfeb54b
    type: content
  - name: Careers
    id: 676ee7a1-eaf3-4bc4-a444-55c0af12d8e9
    type: content
  - name: Search all properties
    url: 'http://www.rrem.com/$frame.html?http%3A%2F%2Fwww.showcase.com'
    type: external
title: Commercial Leasing & Property Management
description: 'Commercial brokerage firm in Rockville, Maryland'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#202121'
    - '#f02300'
    - '#669dc6'
    - '#0071a0'
    - '#fff3ce'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 0.22792554483748972
purpose: []
