typography_spectrum: 0.91482571978122
color:
  brandStrength: 0.4641054505482316
  lightness: 0.9038210313301533
  saturation: 0.796617443440482
  rhythmicContrast: 0.22792554483748972
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
layout_spectrum: 0.5868037801701576
author:
  name: Frank Landolt
  email: flandolt@rrem.com
  url: ''
name: Rollins Real Estate Management
navigation:
  - name: Services
    id: b3974b0b-e020-4739-8a4c-6f90b30308fd
    type: content
  - name: Fairland
    id: 60552014-7f8d-4dae-95ec-1fad8dfeb54b
    type: content
  - name: Careers
    id: 676ee7a1-eaf3-4bc4-a444-55c0af12d8e9
    type: content
  - name: Search all properties
    url: 'http://www.rrem.com/$frame.html?http%3A%2F%2Fwww.showcase.com'
    type: external
title: Commercial Leasing & Property Management
description: 'Commercial brokerage firm in Rockville, Maryland'
